# This code does the following:

#1 load libraries
#2. Read in static data
#3 extract/process data from data.act.gov.au
#4 extract/process site metadata from data.act.gov.au
#5 Create UI
#6 Create Server

#1 Load libraries

library(dplyr)
library(tidyr)
library(RSocrata)
library(soql)
library(lubridate)
library(ggplot2)
library(shiny)

#2. Read in static data

Static_data <- read.csv("Rainfall_data.csv", header = T)
Static_data$Value <- as.numeric(Static_data$Value)
Static_data$DatetimeAEST <- as.POSIXct(Static_data$DatetimeAEST, format = "%Y-%m-%dT%H:%M:%S")
Static_data$DatetimeAEST <- as_date(Static_data$DatetimeAEST)
Static_data$SiteID <- as.factor(Static_data$SiteID)


#3 Extract and process data from data.act.gov.au
# This code uses the RSocrate API. It can be used to extract both the data and the metadata

Query <- soql() %>%
  soql_add_endpoint("https://www.data.act.gov.au/resource/yuhh-28ai.json") %>%
  soql_simple_filter("VariableName", "Rainfall") %>%
  soql_where("DatetimeAEST" > "LAST_YEAR") %>% #fix this somehow
  soql_select("DatetimeAEST, Value, SiteID") %>%
  as.character()

Rainfall_data <- read.socrata(Query)
#write.csv(Rainfall_data, "rainfall_data.csv", row.names = FALSE)

#Prep data
Rainfall_data$Value <- as.numeric(Rainfall_data$Value)
Rainfall_data$DatetimeAEST <- as.POSIXct(Rainfall_data$DatetimeAEST, format = "%Y-%m-%dT%H:%M:%S")
Rainfall_data$DatetimeAEST <- as_date(Rainfall_data$DatetimeAEST)
Rainfall_data$SiteID <- as.factor(Rainfall_data$SiteID)

#merge static and new data

Rainfall_data <- bind_rows(Static_data, Rainfall_data)

#4// Extract metadata from data.act.gov.au

Query2 <- soql() %>%
  soql_add_endpoint("https://www.data.act.gov.au/resource/tsq4-63ge.json") %>%
  soql_select("Siteid, siteName, latitude, longitude") %>%
  as.character()

My_meta <- read.socrata(Query2)

My_meta$Siteid <- as.factor(My_meta$Siteid)
My_meta$latitude <- as.numeric(My_meta$latitude)
My_meta$longitude <- as.numeric(My_meta$longitude)

#filter to relevant sites in the Rainfall dataset
My_meta <- My_meta[My_meta$Siteid %in% Rainfall_data$SiteID,]


##5// UI

ui <- fluidPage(titlePanel("ACT Rainfall Explorer"),
                sidebarLayout(
                  sidebarPanel(
                    
                    # Select site to plot
                    selectInput(inputId = "site", label = strong("Rain Gauge"),
                                choices = unique(My_meta$Siteid),
                                selected = "410776"),
                    
                    # Select date range to be plotted
                    sliderInput("Date", strong("Date range"), min = as.Date("1980-01-01"), max = as.Date("2016-12-31"),
                                value = c(as.Date("1980-01-01"), as.Date("2016-12-31")),
                                timeFormat = "%Y-%m-%d")
                    ),
                    
                  
                  # Output: Description, lineplot, and reference
                  mainPanel(
                    plotOutput(outputId = "lineplot", height = "400px"),
                    plotOutput(outputId = "cumplot", height = "400px"),
                    tags$body("Data provided by ACT Government. Gauged streamflow data generated by in-situ streamflow gauges. 
                              Modelled streamflow is derived from the ACT Government Source catchment model (Predevelopment Scenario),
                              which models streamflow in the absense of all water resource development and land-use change")
                    )
                    )
                  )



#6// Define server function
server <- function(input, output, session) {
  
  # Subset data by site
  selected_rain <- reactive({
    Rainfall_data %>%
      filter(
        SiteID == input$site
        )

  })
  
  #Update slider input to reflect site selected
  observeEvent(input$site, {
  updateSliderInput(session, "Date", value = c(min(selected_rain()$DatetimeAEST), max(selected_rain()$DatetimeAEST)),
                    min = min(selected_rain()$DatetimeAEST), max = max(selected_rain()$DatetimeAEST))
})

  #subset data by selected daterange
  selected_rain2 <- reactive({
  req(input$Date)
  validate(need(!is.na(input$Date[1]) & !is.na(input$Date[2]), "Error: Please provide both a start and an end date."))
  validate(need(input$Date < input$Date[2], "Error: Start date should be earlier than end date."))
  selected_rain() %>%
    filter(DatetimeAEST > input$Date[1] & DatetimeAEST < input$Date[2]
    )
  
})  
  
#  https://stackoverflow.com/questions/48633984/pass-a-dynamic-date-date-range-to-daterangeinput-in-r-shiny
  
  # Create scatterplot object the plotOutput function is expecting
  output$lineplot <- renderPlot({
    ggplot(selected_rain2()) +
      geom_col(aes(x = DatetimeAEST, y = Value), color = "blue") +
      labs(x = "Date", y = "Daily Rainfall (mm)", title = paste0("Rainfall at ", input$site))
  })
}  
  #Create cumulative flow plot
  #output$cumplot <- renderPlot({
   # ggplot(selected_rain()) + 
    #  geom_line(aes(DatetimeAEST, cumsum(replace_na(Value,0)), color = "blue")) +
     # labs(x = "Date", y = "Cumulative flow (GL)", title = paste("Cumulative flow at", (input$site))) + 
      #scale_color_manual(values = c("blue", "red"), labels = c("Gauged cumulative flow", "Modelled cumulative flow"), name = "Legend")
#  })
#                              }

# Create Shiny object
shinyApp(ui = ui, server = server)




